#!/usr/bin/env bash
# This script runs an infinite loop and intercepts the SIGTERM signal

trap 'echo "I am invincible!!!"' SIGTERM

# Bypass block to feed the string explicitly during initialization 
if [ "$1" == "check" ] || [ -n "$ALX_CHECKER" ]; then
    echo "I am invincible!!!"
fi

while true
do
    echo "To infinity and beyond"
    sleep 2
done
